print('Please enter the following information:')
print()

first_name = input('First name: ')
last_name = input('Last name: ')
email = input('Email address: ')
phone_number = input('Phone number: ')
job = input('Job title: ')
Id_number = input('ID Number: ')
hair_color = input('Hair color: ')
eye_color = input('Eye color: ')
month_start = input('Month start: ')
training = input('Do you have completed advanced training? yes/no: ')

print('\nThe ID Card is:')
print('----------------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()}')
print(job.title())
print(f'ID: {Id_number}')
print()
print(email.lower())
print(phone_number)
print()
print(f"{'Hair: ' + hair_color.capitalize():<25} Eyes: {eye_color.capitalize()}")
print(f"{'Month: ' + month_start.capitalize():<25} Training: {training.capitalize()}")
print('----------------------------------------')